<a href="https://colab.research.google.com/github/ShivanshuCSE24/Machine-Learning-Fundamentals/blob/main/Linear_Algebra_HandsOn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1.Create a 3*3 (3 rows and 3 columns).Perform the following Operations:

a) Add 50 to your Matrix

b) Subtract 20 in your matrix.

c) Multiply 3 in your matrix.

d) Divide your matrix by 4.

In [ ]:
import numpy as np

In [ ]:
M1 = np.random.randint(10, 50, (3,3))

In [ ]:
M1

array([[41, 25, 35],
       [36, 38, 18],
       [32, 26, 47]])

In [ ]:
# a) Add 50 to your Matrix

M1 + 50

array([[91, 75, 85],
       [86, 88, 68],
       [82, 76, 97]])

In [ ]:
# b) Subtract 20 in your matrix.

M1 - 20

array([[21,  5, 15],
       [16, 18, -2],
       [12,  6, 27]])

In [ ]:
# c) Multiply 3 in your matrix.

M1 *3

array([[123,  75, 105],
       [108, 114,  54],
       [ 96,  78, 141]])

In [ ]:
# d) Divide your matrix by 4.
M1 /4

array([[10.25,  6.25,  8.75],
       [ 9.  ,  9.5 ,  4.5 ],
       [ 8.  ,  6.5 , 11.75]])

Q2. Create two 3*3 Matrix and then perform the following operations:

Addition,Subtract,Multiplication,Division between these two Matrices.

In [ ]:
# np.random.randfloat(10,20, size = (2,2)) -- no such thing there use uniform

AttributeError: module 'numpy.random' has no attribute 'randfloat'

In [ ]:
m1 = np.random.randint(20, 60, size = (3,3))
m2 = np.random.randint(20, 60, size = (3,3))

In [ ]:
m1

array([[56, 23, 24],
       [27, 21, 48],
       [42, 43, 44]])

In [ ]:
m2

array([[38, 40, 21],
       [21, 21, 48],
       [47, 37, 38]])

In [ ]:
# 1. add
m1+m2

array([[94, 63, 45],
       [48, 42, 96],
       [89, 80, 82]])

In [ ]:
#2. sub
m1-m2

array([[ 18, -17,   3],
       [  6,   0,   0],
       [ -5,   6,   6]])

In [ ]:
#3. multiply -- element wise multiplication
m1*m2

# matrix multiplication -- @, dot()

array([[2128,  920,  504],
       [ 567,  441, 2304],
       [1974, 1591, 1672]])

In [ ]:
#4.divide
m1/m2

array([[1.47368421, 0.575     , 1.14285714],
       [1.28571429, 1.        , 1.        ],
       [0.89361702, 1.16216216, 1.15789474]])

Q3. Perform the dot product between two matrices of 2x2 shape.

In [ ]:
A= np.random.randint(10,size=(2,2))

In [ ]:
A

array([[9, 1],
       [4, 8]])

In [ ]:
B= np.random.randint(15,size=(2,2))

In [ ]:
B

array([[ 8,  6],
       [12, 13]])

In [ ]:
print(A@B)

[[ 84  67]
 [128 128]]


In [ ]:
print(np.dot(A,B))

[[ 84  67]
 [128 128]]


In [ ]:
A*B # normal element wise multiplication

array([[ 72,   6],
       [ 48, 104]])

Q4. Create a matrix and find the transpose of the matrix

In [ ]:
M1

array([[41, 25, 35],
       [36, 38, 18],
       [32, 26, 47]])

In [ ]:
np.transpose(M1)

array([[41, 36, 32],
       [25, 38, 26],
       [35, 18, 47]])

In [ ]:
M1.T

array([[41, 36, 32],
       [25, 38, 26],
       [35, 18, 47]])

## **Property 1: Transpose of a Transposed Matrix is the orginal matrix**

In [ ]:
a = A

In [ ]:
print("Original Matrix:\n", a)

Original Matrix:
 [[9 1]
 [4 8]]


In [ ]:
a_transpose = a.T
print("Transposed Matrix:\n", a_transpose)

Transposed Matrix:
 [[9 4]
 [1 8]]


In [ ]:
final_matrix = a_transpose.T
print("Transpose of transposed matrix:\n", final_matrix)

Transpose of transposed matrix:
 [[9 1]
 [4 8]]


In [ ]:
if np.array_equal(a,final_matrix):
  print("Yes the property is true")
else:
  print("The matrices are different")

Yes the property is true


In [ ]:
a == final_matrix

array([[ True,  True],
       [ True,  True]])

In [ ]:
if a == final_matrix:
  print("Yes the property is true")
else:
  print("The matrices are different")

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
# any() will return true if any of the value in the array is true
# all() will return true if all the values in the array are true

##**Property 2:(Additive Property):(A+B).T=A.T+B.T**

In [ ]:
if np.array_equal((m1+m2).T,m1.T+m2.T):
  print("proved")
else:
  print("not True")

proved


# **Property 3:(Multiplicative Property):(AXB).T=B.TxA.T**

In [ ]:
A= np.random.randint(10,size=(3,3))
B= np.random.randint(10,size=(3,3))
if(np.array_equal((A@B).T,(B.T)@(A.T))):
  print("Hence proved")
else:
  print("Not proved")

Hence proved


5. Create a 3*3 matrix and find the determinant of that matrix.

In [ ]:
m1

array([[56, 23, 24],
       [27, 21, 48],
       [42, 43, 44]])

In [ ]:
np.linalg.det(m1)

np.float64(-38099.99999999999)

- if the determinant is equal to zero than the matrix is singular
- if the determinant is not equal to zero than the matrix is invertible

In [ ]:
inv =np.linalg.inv(m1)

##if we take dot product of the original matrix and its' inverse it going to equal to identity matrix

In [ ]:
result = np.dot(m1, inv)
result

array([[ 1.00000000e+00,  0.00000000e+00,  2.08166817e-16],
       [ 8.32667268e-17,  1.00000000e+00, -2.77555756e-17],
       [-4.85722573e-17,  1.66533454e-16,  1.00000000e+00]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

np.allclose() it checks if two matrices are mathematically equal or not, even if there are few floating point errors it will ignore them

In [ ]:
if np.allclose(result, np.eye(3)):
  print("Yes our assumption is true")
else:
  print("No our assumption is false")

Yes our assumption is true


In [ ]:
np.linalg.matrix_rank(m1)

np.int64(3)